version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      DB_USER: postgres
      DB_PASSWORD: ""
      DB_HOSTNAME: postgres
      DB_PORT: 5432
      DB_NAME: postgres

volumes:
  postgres_data:
