version: '3'

services:
    backend:
        container_name: 
            nc_backend
        image: 
            nc_backend_image
        build:
            context: ./server
        volumes:
            - ./app:/app
        ports:
            - "8088:8088"
        restart: 
            unless-stopped
    db:
        container_name: 
            nc_db
        image: 
            postgres:12
        volumes:
            - db-data:/var/lib/postgresql/data
        restart: 
            unless-stopped
        # Remove at production, add password and env file
        environment: 
            POSTGRES_USER: reddevil
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: neighbourhood_db

volumes:
    db-data: